steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - "--platform=linux/amd64"
      - "--build-arg"
      - "BASE_IMAGE=quay.io/sclorg/python-312-c9s:c9s"
      - "--file"
      - "Dockerfile"
      - "--tag"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/docling-gpu:$SHORT_SHA"
      - "."

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - "us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/docling-gpu:$SHORT_SHA"

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/docling-gpu:$SHORT_SHA"