steps:
  - name: 'gcr.io/cloud-builders/docker'
    env: ['DOCKER_BUILDKIT=1']
    args:
      - build
      - --progress=plain
      - --tag
      - gcr.io/$PROJECT_ID/my-gpu-app
      - .
images:
  - 'gcr.io/$PROJECT_ID/my-gpu-app'