steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'buildx', 'build',
      '--platform', 'linux/amd64',
      '--tag', 'gcr.io/$PROJECT_ID/docling-serve',
      '--load',
      '.'
    ]
images:
  - 'gcr.io/$PROJECT_ID/docling-serve'