steps:
  - name: 'gcr.io/cloud-builders/docker'
    # BuildKit is optional but fine to keep
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      - 'build'
      # Here we skip the CPU extra so that GPU (cu124) is installed
      - '--build-arg'
      - 'UV_SYNC_EXTRA_ARGS=--skip=cpu'
      - '-t'
      - 'gcr.io/$PROJECT_ID/docling-serve'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/docling-serve'